spring.application.name=prasthanam-tours-backend
spring.data.mongodb.uri=mongodb://raghavsohani1995_db_user:CSSlnkZpcPhb9BnR@ac-theyjjh-shard-00-00.ojn6lxo.mongodb.net:27017,ac-theyjjh-shard-00-01.ojn6lxo.mongodb.net:27017,ac-theyjjh-shard-00-02.ojn6lxo.mongodb.net:27017/prasthanam_tours?ssl=true&replicaSet=atlas-12g150-shard-0&authSource=admin&retryWrites=true&w=majority
server.port=8081


